-- Conversation persistence for webui
-- Run: psql -U postgres nobody < schema.sql

CREATE EXTENSION IF NOT EXISTS vector;

-- A conversation session (one for now, many later)
CREATE TABLE sessions (
  id SERIAL PRIMARY KEY,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Every message in/out, in order
CREATE TABLE messages (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id),
  role TEXT NOT NULL,              -- user, assistant, system, tool
  content JSONB NOT NULL,          -- raw Responses API shape
  metadata JSONB,                  -- injected flag, triage results, source, etc.
  embedding VECTOR(1536),          -- for pgvector, backfill later
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_messages_session ON messages(session_id, created_at);
CREATE INDEX idx_messages_role ON messages(session_id, role);

-- Summaries generated by the local model
CREATE TABLE summaries (
  id SERIAL PRIMARY KEY,
  session_id INTEGER NOT NULL REFERENCES sessions(id),
  from_message_id INTEGER REFERENCES messages(id),
  to_message_id INTEGER REFERENCES messages(id),
  summary TEXT NOT NULL,
  embedding VECTOR(1536),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed the single session
INSERT INTO sessions (name) VALUES ('default');
